Feature/rla 10
Emilce-Cano/RefactoringLifeAcademy pull request #25
Opened 2024-07-10 04:21 UTC by claudiocastilloher

Se crea un nuevo Pr, agregando el msj_error.xml con include en activity_Login

![ActivityLogin](https://github.com/Emilce-Cano/RefactoringLifeAcademy/assets/107433152/6db01923-b8e5-4a56-b699-b6fdf187ed33)

2024-07-10 05:52 UTC, reinierdearmas requested changes

2024-07-10 05:52 UTC, reinierdearmas commented on app/src/main/java/com/example/refactoringlifeacademy/ui/login/presenter/LoginActivity.kt
> +                is LoginState.Succes -> {
Agrega que sea GONE el progressbar de Loading
Agrega la navegacion a la Home Activity

2024-07-10 05:52 UTC, reinierdearmas commented on app/src/main/java/com/example/refactoringlifeacademy/ui/login/presenter/LoginActivity.kt
> +                is LoginState.Error -> {
Agrega el GONE al progressbar de Loading
Agrega el VISIBLE al xml de Error

2024-07-10 05:52 UTC, reinierdearmas commented on app/src/main/java/com/example/refactoringlifeacademy/ui/login/presenter/LoginActivity.kt
> +                is LoginState.Loading -> {
Agrega el VISIBLE del progressbar
Agrega el GONE del xml de error

2024-07-10 05:52 UTC, reinierdearmas commented on app/src/main/res/layout/activity_register.xml
> +        android:layout_marginStart="42dp"
Por que agregas codigo al layout de register???

2024-07-10 05:52 UTC, reinierdearmas commented on app/src/main/res/layout/activity_user_or_password_error.xml
No se para que es este XML no le encontre el hilo.

2024-07-11 04:45 UTC, claudiocastilloher commented on app/src/main/res/layout/activity_user_or_password_error.xml
Se había creado debido a que al incio el mensaje de error y el progressbar se usaban directamente desde los textview  y progressbar en la pantallapor ejemplo login

2024-07-11 04:45 UTC, claudiocastilloher commented on app/src/main/java/com/example/refactoringlifeacademy/ui/login/presenter/LoginActivity.kt
> +                is LoginState.Succes -> {
Se atiende.

2024-07-11 04:45 UTC, claudiocastilloher commented on app/src/main/java/com/example/refactoringlifeacademy/ui/login/presenter/LoginActivity.kt
> +                is LoginState.Error -> {
Se atiende.

2024-07-11 04:45 UTC, claudiocastilloher commented on app/src/main/java/com/example/refactoringlifeacademy/ui/login/presenter/LoginActivity.kt
> +                is LoginState.Loading -> {
Se atiende.

2024-07-11 04:45 UTC, claudiocastilloher commented on app/src/main/res/layout/activity_register.xml
> +        android:layout_marginStart="42dp"
En el msj_error se eliminó la propiedad Gravity Center para poder alinear el mensaje de error en el login Activity.

2024-07-11 04:45 UTC, closed without merging