Feature/rla 012
Emilce-Cano/RefactoringLifeAcademy pull request #32
Opened 2024-07-16 23:04 UTC by Emilce-Cano

### Description 

-se realizo el xml de image fragment
-se creo adapter de recylcer
-constrol de estados 
![image](https://github.com/user-attachments/assets/e0aef939-9d58-41f1-881d-0ebe4c2a659e)

2024-07-17 06:10 UTC, reinierdearmas requested changes

2024-07-17 06:10 UTC, reinierdearmas commented on app/src/main/java/com/example/refactoringlifeacademy/ui/detail/presenter/ImageFragment.kt
> +                    state.data?.images?.let { images ->
Cuando la imagen sea null o vacia hay que cargar esta imagen

![Captura de pantalla (97)](https://github.com/user-attachments/assets/b39ad61f-ce2a-41b7-ac58-c416d2593b98)

2024-07-18 01:01 UTC, ValRomS commented on app/src/main/java/com/example/refactoringlifeacademy/ui/detail/presenter/viewmodel/adapter/ProductImageAdapter.kt
> +        holder.render(image)
Podrías meter images[position] directamente en la función render, así te evitas crear variable

2024-07-18 01:01 UTC, ValRomS commented on app/src/main/java/com/example/refactoringlifeacademy/ui/detail/presenter/viewmodel/adapter/ProductImageAdapter.kt
> +        holder.render(image)
Podrias meter images[position] directamente en la función render, así te evitas crear variable

2024-07-18 01:03 UTC, ValRomS approved these changes

2024-07-23 04:17 UTC, reinierdearmas approved these changes

2024-07-23 04:20 UTC, merged