Feature/rla-5 Solicito la revision para añadir al develop mi aporte
Emilce-Cano/RefactoringLifeAcademy pull request #4
Opened 2024-06-04 06:44 UTC by ValRomS

Interfaz terminada, favor de avisar si algo no esta bien.

![image](https://github.com/Emilce-Cano/RefactoringLifeAcademy/assets/148787829/559f914b-7579-47e7-8859-bef630f1f088)

2024-06-04 16:01 UTC, Emilce-Cano requested changes
esta todo bien. solo esos detalles faltaria.

2024-06-04 16:01 UTC, Emilce-Cano commented on app/src/main/res/layout/activity_register.xml
lo unico que falta es el color de tu register. esta en gris.

2024-06-04 16:01 UTC, Emilce-Cano commented on app/src/main/res/layout/activity_register.xml
> +        android:id="@+id/tvRegister"
seria aca lo del color

2024-06-04 16:01 UTC, Emilce-Cano commented on app/src/main/res/layout/activity_register.xml
en algunos de los edittex y otros elementos tiene solo un constrain unido. si es posible que minimo tenga almenos dos guias. dos constraint

2024-06-04 22:50 UTC, Emilce-Cano approved these changes
todo ok!

2024-06-05 02:55 UTC, reinierdearmas reviewed
De forma general veo todo bien, te sugiero emplear Binding que ya esta habilitado en el Proyecto.

2024-06-05 04:47 UTC, reinierdearmas approved these changes

2024-06-05 04:50 UTC, merged