Feature/rla 7
Emilce-Cano/RefactoringLifeAcademy pull request #8
Opened 2024-06-06 04:31 UTC by reinierdearmas

Actividad RLA-7 Validacion de Email y Contraseña del Register. Se empleo una Clase String con extension de funciones, expresiones regulares para validar los diferentes campos, corrutinas y observer. Las expresiones regulares pueden ser comprobadas en https://regex101.com/.

2024-06-06 04:38 UTC, nisias approved these changes

2024-06-06 06:36 UTC, Emilce-Cano approved these changes

2024-06-06 13:35 UTC, KevinMaggio requested changes

2024-06-06 13:35 UTC, KevinMaggio commented on app/src/main/java/com/example/refactoringlifeacademy/utils/StringUtils.kt
![image](https://github.com/Emilce-Cano/RefactoringLifeAcademy/assets/86111731/b797a284-f52c-4595-addc-0c95ec4a3ae2)
no hace falta el uso de un Singleton. 
se puede dejar las funciones sueltas.

2024-06-06 13:35 UTC, KevinMaggio commented on app/src/main/java/com/example/refactoringlifeacademy/viewmodels/RegisterViewModel.kt
![image](https://github.com/Emilce-Cano/RefactoringLifeAcademy/assets/86111731/e180430f-d2a0-4493-a034-76636b7902bf)
estan mal los harcodeos. 

pasar parametros como true. sin saber que sean true esta mal. 

la funcion tiene que pedir los 3 campos al mismo tiempo. 

y cada vez que se llame se le tienen que pasar los 3 campos.  de lo contrario con completar 1 solo va a dar true a los 3

2024-06-06 13:35 UTC, KevinMaggio commented on app/src/main/res/layout/activity_main.xml
![image](https://github.com/Emilce-Cano/RefactoringLifeAcademy/assets/86111731/0a4f88eb-279f-4522-a517-075643abfe7e)
no entiendo por que modificar el ID de este XML

2024-06-06 13:35 UTC, KevinMaggio commented on app/src/main/res/layout/activity_register.xml
![image](https://github.com/Emilce-Cano/RefactoringLifeAcademy/assets/86111731/73e495c8-0823-4909-9117-07b39b277cf3)

CML utiliza un formato snake_case
intentemos mantener el mismo para los ID

2024-06-06 14:15 UTC, reinierdearmas commented on app/src/main/java/com/example/refactoringlifeacademy/utils/StringUtils.kt
En la investigación que realicé lo sugerian si se querian emplear las funciones de extensión en todo el proyecto. Lo pensé como una alternativa para que pudiera ser usado en actividades similares como el login.

2024-06-06 14:21 UTC, reinierdearmas commented on app/src/main/res/layout/activity_main.xml
Este id fue algo que modifique para hacer mis pruebas de forma local de la activación desactivación del botón y necesitaba navegar hacia register y por tanto el onclick sobre el tv lo tenia que manejar por el id y después se quedó cuando hice commit pero lo arreglo.

2024-06-06 14:23 UTC, reinierdearmas commented on app/src/main/res/layout/activity_register.xml
Lo corrijo

2024-06-06 14:33 UTC, reinierdearmas commented on app/src/main/java/com/example/refactoringlifeacademy/viewmodels/RegisterViewModel.kt
En este caso vere como corregir para que una sola corrutina este actualizando el valor del livedata que incluya los 3 textwatch

2024-06-07 15:44 UTC, Emilce-Cano reviewed
el view model es diferente al mio ya que separas las logicas de validacion del formulario. lo veo bastante bien.  solo que necesita una mirada de un Profesional.

2024-06-07 23:48 UTC, ValRomS approved these changes

2024-06-08 00:42 UTC, KevinMaggio requested changes

2024-06-08 00:42 UTC, KevinMaggio commented on app/src/main/java/com/example/refactoringlifeacademy/utils/StringUtils.kt
![image](https://github.com/Emilce-Cano/RefactoringLifeAcademy/assets/86111731/618edf54-9e3d-4715-a543-e21c3138ab29)
Eliminar todo el codigo comentado

2024-06-08 00:42 UTC, KevinMaggio commented on app/src/main/java/com/example/refactoringlifeacademy/viewmodels/RegisterViewModel.kt
![image](https://github.com/Emilce-Cano/RefactoringLifeAcademy/assets/86111731/cd3f7d6c-0e21-4995-a28a-4d78d0d60c8d)

Solo comentar funciones extremadamente complejas. y en ingles

2024-06-08 00:42 UTC, KevinMaggio commented on app/src/main/res/layout/activity_register.xml
![image](https://github.com/Emilce-Cano/RefactoringLifeAcademy/assets/86111731/5af4c35f-09a4-449d-9f7d-baac2fa40bdc)
esta escrito con 3 T buTTTon_Register

tambien tiene R en mayus

2024-06-08 15:38 UTC, merged