Feature/rla 6
Emilce-Cano/RefactoringLifeAcademy pull request #9
Opened 2024-06-07 14:55 UTC by Emilce-Cano

## Description
se realizo validaciones de los campos de login, tambien se modifico utilsString la parte de validacion de campo de password
y el la Activity se implemento observer con el viewmodel para pasar a la otra pantalla. 

### Evidence
![image](https://github.com/Emilce-Cano/RefactoringLifeAcademy/assets/108499163/287abfab-b48f-4689-aa5c-fe1b995bcb6e)
 lo del comentario de esto no me esta haciendo el checkeo era para hacerme acordar que no habia inicializado aun la funsion. para despues probarlo e inicializarlo. 
ya lo probe anda todo.

2024-06-09 17:19 UTC, reinierdearmas commented on app/src/main/java/com/example/refactoringlifeacademy/ui/activity/LoginActivity.kt
Aqui la actualizacion de los campos email y password se produce al hacer click en el boton de login cuando lo que se pide es activar el boton cuando el email y el password esten conformados correctamente y es entonces cuando podras hacer click. Se le pudiera consultar si puede ser logrado asi tambien porque lo cierto es que debe funcionar pero conceptualmente es diferente lo que sucede.

2024-06-09 17:23 UTC, reinierdearmas commented on app/src/main/java/com/example/refactoringlifeacademy/utils/StringUtils.kt
Aqui Kevin mando a quitar el singleton y los comentarios, y dejar las funciones suletas, fijate en la rama RLA-7 como estan definidas las funciones de extension. Ademas en la valdacion del password es conveniente utilizar la expresion regular proporcionada por el equipo de backend incorporando dentro de la expresion que tengan entre 8 y 20 caracteres y asi evitar tantas condiciones, con esa expresion se puede lograr la validacion completa.

2024-06-09 17:25 UTC, reinierdearmas commented on app/src/main/java/com/example/refactoringlifeacademy/ui/viewmodels/RegisterViewModel.kt
Pineso que despues de ajustar los cambios sugeridos en el util, se pueden emplear las funciones de forma comun en los viewmodels del login y register.

2024-06-09 17:26 UTC, reinierdearmas commented on app/src/main/res/layout/activity_main.xml
Aqui imagino que tiene que ver con el espacio que exige git??? y a eso se debe el cambio.

2024-06-09 17:27 UTC, reinierdearmas commented on app/build.gradle.kts
Aqui no se que cambio, no me doy cuenta.

2024-06-09 17:50 UTC, reinierdearmas requested changes

2024-06-09 17:50 UTC, reinierdearmas commented on app/src/main/java/com/example/refactoringlifeacademy/ui/activity/LoginActivity.kt
> +        binding.btnEnter.setOnClickListener {
Aqui la actualizacion de los campos email y password se produce al hacer click en el boton de login cuando lo que se pide es activar el boton cuando el email y el password esten conformados correctamente y es entonces cuando podras hacer click. Se le pudiera consultar si puede ser logrado asi tambien porque lo cierto es que debe funcionar pero conceptualmente es diferente lo que sucede.

2024-06-09 17:50 UTC, reinierdearmas commented on app/src/main/java/com/example/refactoringlifeacademy/ui/viewmodels/RegisterViewModel.kt
> +import com.example.refactoringlifeacademy.utils.StringUtils.isValidEmail
Pineso que despues de ajustar los cambios sugeridos en el util, se pueden emplear las funciones de forma comun en los viewmodels del login y register.

2024-06-09 17:50 UTC, reinierdearmas commented on app/src/main/java/com/example/refactoringlifeacademy/ui/viewmodels/RegisterViewModel.kt
> +import com.example.refactoringlifeacademy.utils.StringUtils.isValidEmail
Pineso que despues de ajustar los cambios sugeridos en el util, se pueden emplear las funciones de forma comun en los viewmodels del login y register.

2024-06-09 17:50 UTC, reinierdearmas commented on app/src/main/java/com/example/refactoringlifeacademy/utils/StringUtils.kt
> +object StringUtils {
Aqui Kevin mando a quitar el singleton y los comentarios, y dejar las funciones suletas, fijate en la rama RLA-7 como estan definidas las funciones de extension.

2024-06-09 17:50 UTC, reinierdearmas commented on app/src/main/java/com/example/refactoringlifeacademy/utils/StringUtils.kt
> +    fun String.isValidPassword(): Boolean {
Ademas en la valdacion del password es conveniente utilizar la expresion regular proporcionada por el equipo de backend incorporando dentro de la expresion que tengan entre 8 y 20 caracteres y asi evitar tantas condiciones, con esa expresion se puede lograr la validacion completa.

2024-06-10 17:59 UTC, reinierdearmas commented on app/src/main/java/com/example/refactoringlifeacademy/utils/StringUtils.kt
> +    fun String.validationEmail(): Boolean {
Ya el patron de validacion de Email que proporciona kotlin tiene en cuenta el resto de las condiciones que evaluas, me parece que con solo evaluar que coincida con ese patron es suficiente. Por que ajustar a no mas de 30 caracteres del email?

2024-06-10 18:03 UTC, reinierdearmas commented on app/src/main/java/com/example/refactoringlifeacademy/utils/StringUtils.kt
> +    fun String.isValidPassword(): Boolean {
Por que la resistencia de usar una expresion regular para validar el Password que contenga todas las condiciones. Me parece mas eficiente que estar comprobando cada una de las condicones. Emplear la misma funcion de validacion del password en el viewmodel del Register, no creo que hagan falta dos funciones para cumplir con un mismo objetivo.

2024-06-10 18:08 UTC, reinierdearmas commented on app/src/main/java/com/example/refactoringlifeacademy/utils/StringUtils.kt
> +        if (this.length !in 8..20) return false
Por que la resistencia de usar una expresion regular para validar el Password que contenga todas las condiciones. Me parece mas eficiente que estar comprobando cada una de las condicones.

2024-06-10 18:09 UTC, reinierdearmas commented on app/src/main/java/com/example/refactoringlifeacademy/utils/StringUtils.kt
> +    fun String.validationEmail(): Boolean {
Ya el patron de validacion de Email que proporciona kotlin tiene en cuenta el resto de las condiciones que evaluas, me parece que con solo evaluar que coincida con ese patron es suficiente. Por que ajustar a no mas de 30 caracteres del email?. Pienso que esta validacion tambien debe ser empleada en el Viewmodel del Register, no hace falta tener dos validaciones para un mismo campo, incorporar los cambios en el viewmodel del Register como mismo se hizo para el caso del password.

2024-06-10 21:03 UTC, reinierdearmas approved these changes

2024-06-10 21:07 UTC, ValRomS approved these changes

2024-06-10 21:07 UTC, merged